export const ercbalance = {
    libraryAddress: "0xE8BB32A0A9B69C95D68Bf8890f3ff5fbB46a691b",
    abi: [
        { inputs: [], name: "TokenOwnerError", type: "error" },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
            ],
            name: "ERC1155Allowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
                { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "ERC1155RequirementsTrue",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
            ],
            name: "ERC1155_Balance",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "address", name: "spender", type: "address" },
            ],
            name: "ERC20Allowance",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "spender", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "ERC20RequirementsTrue",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
            ],
            name: "ERC20_Balance",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
            ],
            name: "ERC721Allowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
            ],
            name: "ERC721AllowanceAll",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
            ],
            name: "ERC721RequirementsTrue",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
            ],
            name: "ERC721_Balance",
            outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
            ],
            name: "hasEnoughERC1155Allowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "address", name: "spender", type: "address" },
                { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "hasEnoughERC20Allowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "operator", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
            ],
            name: "hasEnoughERC721Allowance",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
                { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "ownsERC1155Amount",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "amount", type: "uint256" },
            ],
            name: "ownsERC20Amount",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
        {
            inputs: [
                { internalType: "address", name: "_tokenAddress", type: "address" },
                { internalType: "address", name: "_owner", type: "address" },
                { internalType: "uint256", name: "tokenId", type: "uint256" },
            ],
            name: "ownsERC721token",
            outputs: [{ internalType: "bool", name: "", type: "bool" }],
            stateMutability: "view",
            type: "function",
        },
    ],
};
